services:
  mysql:
    image: mysql:8.0
    container_name: todoapp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todoapp
      MYSQL_USER: todouser
      MYSQL_PASSWORD: todopassword
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone='+09:00'
    networks:
      - todoapp-network

  redis:
    image: redis:7-alpine
    container_name: todoapp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - todoapp-network

volumes:
  mysql_data:
  redis_data:

networks:
  todoapp-network:
    driver: bridge